### ISSUE TITLE
Documentation gschecker

### ISSUE THREAD

**Issue by gryckelynck** [geopicardie/gschecker#5]
Il manque un minimum de documentation pour prendre le script en main.
Voici mes notes si ça peut servir:

## Installation de gschecker:

Cloner le dépôt Git:
```
$ git clone https://github.com/geopicardie/gschecker.git
```

Se placer dans le dossier de l'application:
```
$ cd gschecker
```

Créer un environnement virtuel Python:
```
$ virtualenv venv
```

Activer l'environnement virtuel:
Sous Windows
```
$ venv\Scripts\activate
```
Sous Linux:
```
$ source venv\bin\activate
```

Installer les modules Python nécessaires
```
$ pip install -r requirements.txt
```

## Configuration de gschecker

Créer une copie du fichier `gsconfig_geopicardie.json`
Le renommer en `gsconfig.json` et l'adapter.

Créer un dossier `results` pour stocker les fichiers XML résultants.

**Comment by mlefort** [comment]
Merci je l'intégre au ReadMe
