### ISSUE TITLE
Fusionner les dernières modifications de GéoBretagne et celles de GéoPicardie

### ISSUE THREAD

**Issue by bchartier** [geopicardie/gschecker#6]
Les derniers commits de GéoBretagne et de GéoPicardie mériteraient d'être réconciliés.
Les mises à jour spécifiques sur les templates de métadonnées n'ont pas forcément vocation à être reprises.

**Comment by mlefort** [comment]
Fait manuellement pour les modifs de GeoBretagne sur gschecker.py : changement du logger et passage en https (https://github.com/geobretagne/gschecker/commit/d402511dae3885092d1fab32e55212272c1a38fa)

**Comment by bchartier** [comment]
@fphg : 
mlefort a reporté vos propres commits avec le code sur GéoPicardie manuellement (sans les trucs spécifiques à GéoBretagne).
